//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auktionshus_WPF.Model
{
    using System;
    
    public enum MetalType : int
    {
        Gold = 1,
        Silver = 2,
        Palladium = 3,
        Osmium = 4,
        Iridium = 5,
        Rhodium = 6
    }
}
