//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auktionshus_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOffer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalesOffer()
        {
            this.PurchaseOffers = new HashSet<PurchaseOffer>();
        }
    
        public int Id { get; set; }
        public MetalType MetalType { get; set; }
        public string Amount { get; set; }
        public System.DateTime Deadline { get; set; }
        public Nullable<int> AccountId { get; set; }
    
        public virtual Account Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOffer> PurchaseOffers { get; set; }
    }
}
